# Generated by Django 4.1 on 2022-08-17 15:46

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Dressage', 'Dressage'), ('Show Jumping', 'Show Jumping'), ('Cross Country', 'Cross Country'), ('Eventing', 'Eventing'), ('Western Dressage', 'Western Dressage'), ('Reining', 'Reining'), ('Polo', 'Polo'), ('Horseball', 'Horseball'), ('Combined driving', 'Combined driving'), ('Flat racing', 'Flat racing'), ('Harness racing', 'Harness racing'), ('Skijoring', 'Skijoring'), ('Endurance Racing', 'Endurance Racing'), ('Vaulting', 'Vaulting'), ('Dancing', 'Dancing'), ('Rejoneo', 'Rejoneo')], max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(max_length=2048)),
                ('avg_height', models.FloatField()),
                ('avg_weight', models.FloatField()),
                ('country', models.CharField(max_length=128)),
                ('blood', models.CharField(choices=[('Hot', 'Hot'), ('Cold', 'Cold'), ('Warm', 'Warm')], max_length=16)),
                ('image', models.ImageField(upload_to=pathlib.PurePosixPath('/home/anton/Documentos/projects/python/breed-web/breed_page/breed_page/static'))),
                ('coat', models.ManyToManyField(related_name='breed_to_coats', to='breed_app.coat')),
                ('discipline', models.ManyToManyField(related_name='breed_to_disciplines', to='breed_app.discipline')),
                ('predecessor', models.ManyToManyField(related_name='breed_to_predecessors', to='breed_app.breed')),
            ],
        ),
    ]
